### PR TITLE
Pre-release merge for minor release v0.5.3

### PR DESCRIPTION
**Pull request by mhl10**
This upgrades the arxiv-base dependency to 0.15.2, which in search updates the page footer to the four-column version.

### CODE REVIEW

**Comment by JaimieMurdock** [comment]
The mypy failure is likely related to the fixes I just released into `task/ARXIVNG-1971`. I'll check out the code and test in the next 30 minute to update.

I think the develop branch is protected for direct commits, but if it is related, then a `git cherry-pick 9a1389da21352c77c74b17617287406554783eb0` should pull out the fixes we'd need.

**Comment by mhl10** [comment]
> The mypy failure is likely related to the fixes I just released into `task/ARXIVNG-1971`. I'll check out the code and test in the next 30 minute to update.
> 
> I think the develop branch is protected for direct commits, but if it is related, then a `git cherry-pick 9a1389da21352c77c74b17617287406554783eb0` should pull out the fixes we'd need.

Thanks Jaimie!

**Comment by JaimieMurdock** [comment]
It seems like the issue was resolved by https://github.com/arXiv/arxiv-base/pull/106

`pipenv run mypy -p search | grep -v "test*" | grep -v "defined here"`

returns nothing, which indicates a success.

**Comment by JaimieMurdock** [comment]
I think the latest mypy fixes should make it all work, but it also looks like there's more than just a version bump on arxiv-base that's going into master, based on the number of tickets and commits in the history here. Perhaps we should audit first and get some more release notes together?

**Pull request merged**
