### PR TITLE
Feature/#259 classic api start and max results

### PR DESCRIPTION
**Pull request by alefnula**
These are the fixes in the feed data.

- `max_results`
- `ID` is a hash
- Some refactoring
- timestamp formatting
- small enhancements.

### CODE REVIEW

**Comment by mhl10** [comment]
Thanks @alefnula, I'll review this shortly.

**Comment by alefnula** [comment]
I executed the black formater on some files. If you're against it I'll revert those changes.

If you're up for that, than maybe it's best to run it on the whole repository and then there won't be any changes if I accidentally run it (it's a shortcut that I always do from time to time).

**Comment by alefnula** [comment]
Again I can't merge the code, can you give me access to see what's happening to the `mypy` checks - why they get stuck so I can try to fix it?

**Comment by mhl10** [comment]
> Again I can't merge the code, can you give me access to see what's happening to the `mypy` checks - why they get stuck so I can try to fix it?

Sorry for the trouble. You do have write access; I think this problem has do with protected branches. I'm investigating.

**Comment by mhl10** [comment]
> > Again I can't merge the code, can you give me access to see what's happening to the `mypy` checks - why they get stuck so I can try to fix it?
> 
> Sorry for the trouble. You do have write access; I think this problem has do with protected branches. I'm investigating.

@alefnula for now I've disabled the `code-quality/mypy` status check as a required check. You should be able to see the output by running `lintstats.sh`.

**Pull request merged**
