### PR TITLE
ARXIVNG-1357 Updated DocumentMapping to provide consistent support for secondary category

### PR DESCRIPTION
**Pull request by erickpeirson**
Supported as part of all-field search in simple UI:
image

This basically makes the behavior equivalent to the behavior for primaries.

To test, follow the instructions for local dev deployment of ES using Docker, and use the ``create_index.py`` and ``bulk_index.py`` scripts.

### CODE REVIEW

**Comment by eawoods** [comment]
Something odd going on here -- in search for `matter theory`, primary category labels being searched and hit (as expected, since that's been the prevailing behavior on partials)....but cond-mat categories are also showing hits for some reason?  ???

screen shot 2018-12-03 at 3 07 19 pm

**Comment by erickpeirson** [comment]
"matter" is in the full name for cond-mat, IIRC

**Comment by eawoods** [comment]
Oh, I thought it was "materials". Well, that makes more sense then.

**Comment by erickpeirson** [comment]
> Primary category provides hits on partial but secondary does not

How's this?
image

**Comment by erickpeirson** [comment]
Thanks! Will wait to merge until @mhl10 has a chance to try it out.

**Comment by mhl10** [comment]
> "matter" is in the full name for cond-mat, IIRC

There may be an issue with the highlighting secondary categories, specifically when searching on category labels. For example, when I search for nanoscale physics, I expect to get results and highlights on cond-mat.mes-hall (Mesoscale and Nanoscale Physics).

From http://localhost:5000/advanced?advanced=&terms-0-operator=AND&terms-0-term=nanoscale+physics&terms-0-field=all&classification-physics_archives=all&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=50&order=-announced_date_first

screenshot 2018-12-04 09 32 20

(`cond-mat.mes-hall` not highlighted)

screenshot 2018-12-04 09 32 42

(`quant-ph` highlighted instead of `cond-mat.mes-hall`)

**Comment by mhl10** [comment]
If I narrow the search by subject in the advanced search, I get a `TypeError`; e.g. 

http://localhost:5000/advanced?advanced=&terms-0-operator=AND&terms-0-term=random+walk&terms-0-field=all&classification-computer_science=y&classification-physics_archives=all&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=hide&size=50&order=-announced_date_first

```arxiv-search/search/domain/base.py", line 136, in <listcomp>
[p['id'] for p in [self.group, self.archive, self.category] if p]
TypeError: string indices must be integers```

**Comment by erickpeirson** [comment]
@mhl10 @eawoods Ok, I think I fixed it. Would you mind pulling and trying with a fresh index?

**Comment by erickpeirson** [comment]
Pushed a fix for category bug. We had been abusing the ``Classification`` domain class in a few places.

**Comment by erickpeirson** [comment]
I see in #209 that limiting by archive should take primary into account; I'm actually not sure that's happening yet.

**Comment by mhl10** [comment]
@erickpeirson thanks for the fix in 7362810. One minor problem remains--the case where you narrow by subject area in the advanced search but enter no term, e.g. [this query](http://localhost:5000/advanced?advanced=&terms-0-operator=AND&terms-0-term=&terms-0-field=title&classification-physics=y&classification-physics_archives=all&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=hide&size=50&order=-announced_date_first) returns:

`AttributeError: 'list' object has no attribute 'secondary_classification'`

You had asked where the following represents a regression:
> Including secondaries when limiting for a short-cut route. E.g. /math <-- only looks at primary.

I'll take a closer look at classic search and follow up. Even if it turns out to be a regression, we may be able to live with it for the time being.

**Comment by mhl10** [comment]
> You had asked whether the following represents a regression:
> 
> > Including secondaries when limiting for a short-cut route. E.g. /math <-- only looks at primary.
> 
> I'll take a closer look at classic search and follow up. Even if it turns out to be a regression, we may be able to live with it for the time being.

So it does appear to be a regression, though in my opinion it's a minor one. For example, the second result from [this classic advanced query limited to q-bio](https://arxiv.org/find/grp_q-bio/1/all:+global/0/1/0/all/0/1) shows a paper with a primary in cs and secondary in q-bio.

**Comment by erickpeirson** [comment]
> > You had asked whether the following represents a regression:
> > > Including secondaries when limiting for a short-cut route. E.g. /math <-- only looks at primary.
> > 
> > 
> > I'll take a closer look at classic search and follow up. Even if it turns out to be a regression, we may be able to live with it for the time being.
> 
> So it does appear to be a regression, though in my opinion it's a minor one. For example, the second result from [this classic advanced query limited to q-bio](https://arxiv.org/find/grp_q-bio/1/all:+global/0/1/0/all/0/1) shows a paper with a primary in cs and secondary in q-bio.

@mhl10 I dunno; I'm really tempted to deal with this once and for all.

**Comment by mhl10** [comment]
OK, go for it!

On Dec 18, 2018, at 4:22 PM, Erick <notifications@github.com<mailto:notifications@github.com>> wrote:


You had asked whether the following represents a regression:

Including secondaries when limiting for a short-cut route. E.g. /math <-- only looks at primary.

I'll take a closer look at classic search and follow up. Even if it turns out to be a regression, we may be able to live with it for the time being.

So it does appear to be a regression, though in my opinion it's a minor one. For example, the second result from this classic advanced query limited to q-bio<https://arxiv.org/find/grp_q-bio/1/all:+global/0/1/0/all/0/1> shows a paper with a primary in cs and secondary in q-bio.

@mhl10<https://github.com/mhl10> I dunno; I'm really tempted to deal with this once and for all.

**Comment by erickpeirson** [comment]
Ok kids, pardon all of the pushes. I went ahead and did some minor refactoring to include cross-list classification in filtering. This means that

- cross-list categories should be considered when filtering for short-cut routes, e.g. http://localhost:5000/math
- cross-list categories are optionally (new feature!) considered in the advanced search interface

image

I also went ahead and updated all of the version refs and such.

I think that it was good to do this. It also gave me an opportunity to delete some code, which always feels great.

**Comment by mhl10** [comment]
Thanks, changes look great!

http://localhost:5000/advanced?advanced=&terms-0-operator=AND&terms-0-term=quantum+physics&terms-0-field=all&classification-computer_science=y&classification-physics_archives=all&classification-include_cross_list=include&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=50&order=-announced_date_first

**Pull request merged**
